# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "bento/ubuntu-18.04"

    config.vbguest.auto_update = true
    config.vbguest.no_remote = true

    config.vm.provider "virtualbox" do |vb|
        vb.gui = true

        vb.name = "ubuntu-18.04-gnome"

        vb.memory = "8192"
        vb.cpus = "4"
        vb.customize ["modifyvm", :id, "--vram", "128"]
        vb.customize ["modifyvm", :id, "--accelerate3d", "off"]
        # vb.customize ["modifyvm", :id, "--nic2", "bridged"]

        vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
    end

    config.vm.provision "shell", path: "provision-root.sh"
    config.vm.provision "shell", path: "provision-user.sh", privileged: false
  
end
