# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "bento/ubuntu-16.04"

    config.vbguest.auto_update = true
    config.vbguest.no_remote = true

    config.vm.provider "virtualbox" do |vb|
        vb.gui = true

        vb.name = "ubuntu-16.04-jdk8"

        vb.memory = "8192"
        vb.cpus = "4"
        vb.customize ["modifyvm", :id, "--vram", "128"]
        vb.customize ["modifyvm", :id, "--accelerate3d", "off"]
        vb.customize ["modifyvm", :id, "--nic2", "bridged"]

        vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]

        vb.customize ["storageattach", :id, "--storagectl", "IDE Controller", "--port", "0", "--device", "0", "--type", "dvddrive", "--medium", "emptydrive"]
    end

    config.vm.provision "shell", path: "provision.sh"
    config.vm.provision "shell", path: "provision-umake.sh", privileged: false
  
end
